language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: build
      script:
        - npm run setup
        - npm run build
    - stage: lint
      script:
        - npm run setup
        - npm run lint
    - stage: test
      script:
        - npm run setup
        - npm run build
        - npm run test

stages:
  - build
  - lint
  - test
